name: duvadie
favicon: null
layout_spectrum: 0.8523965317290276
typography_spectrum: 0.8256954671815038
title: DUVADIE Law Office
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#b2b2b2'
    - '#000000'
    - '#5b5b5b'
    - '#1c1c1c'
    - '#ad6f41'
  brandStrength: 0.9539692108519375
  lightness: 0.018658679211512208
  saturation: 0.9887442411854863
  rhythmicContrast: 0.23319521849043667
purpose: []
